Install homebrew from tarball

diff --git a/scripts_installer/postflight.in b/scripts_installer/postflight.in
--- a/scripts_installer/postflight.in
+++ b/scripts_installer/postflight.in
@@ -6,6 +6,7 @@ VNC_PASSWORD=$(uuidgen | sed 's/-//g')
 BASE_URL="@@BASE_URL@@"
 INVENTORY_TAG="@@INVENTORY_TAG@@"
 CLT_FILENAME="Command_Line_Tools_${MACOS_VERSION}.pkg"
+HOMEBREW_FILENAME="@@HOMEBREW_FILENAME@@"
 FUSION_INVENTORY_AGENT_PKG="@@FUSION_INVENTORY_AGENT_PKG@@"
 FUSION_INVENTORY_AGENT_ARCHIVE="@@FUSION_INVENTORY_AGENT_ARCHIVE@@"
 VNC_SERVER_FILENAME="@@VNC_SERVER_FILENAME@@"
@@ -56,7 +57,21 @@ fi
 
 
 # Homebrew
-su - $USER -c '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null'
+if which brew; then
+  # Install Homebrew only if not found
+  curl -O ${BASE_URL}/mac/downloads/${HOMEBREW_FILENAME}
+  if [[ -f ${HOMEBREW_FILENAME} ]];then
+    su - $USER -c 'mkdir -p /usr/local/homebrew'
+    su - $USER -c 'tar xzf "${PREFIX}/${HOMEBREW_FILENAME}" --strip 1 -C /usr/local/homebrew'
+    su - $USER -c 'ln -s /usr/local/homebrew/brew /usr/local/bin/brew'
+  else
+    echo "ERROR: downloaded package ${HOMEBREW_FILENAME} not found"
+    exit 1
+  fi
+  if [ -e ${HOMEBREW_FILENAME} ];then
+    rm -rf ${HOMEBREW_FILENAME}
+  fi
+fi
 
 # Install pip
 easy_install pip
@@ -79,6 +94,7 @@ echo
 if [[ ! -f /bin/rbash ]]; then
   cp "${PREFIX}/rbash" /usr/local/bin/
   chmod +x /usr/local/bin/rbash
+  xattr -d com.apple.quarantine /usr/local/bin/rbash
 fi
 
 # Create pulse user account
@@ -252,6 +268,7 @@ fi
 # Copy launcher
 cp "${PREFIX}/runpulseagent" "${INSTALL_PATH}/bin"
 chmod +x "${INSTALL_PATH}/bin/runpulseagent"
+xattr -d com.apple.quarantine "${INSTALL_PATH}/bin/runpulseagent"
 
 # Copy service descriptor
 cp "${PREFIX}/net.siveo.pulse_xmpp_agent.plist" /Library/LaunchDaemons/
