Fix install of command line tools on macOS

diff --git a/scripts_installer/postflight.in b/scripts_installer/postflight.in
--- a/scripts_installer/postflight.in
+++ b/scripts_installer/postflight.in
@@ -1,10 +1,11 @@
 #!/bin/bash
 PREFIX="$1/Contents/Resources"
-MACOS_VERSION=$(sw_vers |grep ProductVersion|awk '{print $2}')
+MACOS_VERSION=$(sw_vers |grep ProductVersion|awk '{print $2}'|awk -F "." '{print $1"."$2}')
 INSTALL_PATH="/Library/Application Support/Pulse"
 VNC_PASSWORD=$(uuidgen | sed 's/-//g')
 BASE_URL="@@BASE_URL@@"
 INVENTORY_TAG="@@INVENTORY_TAG@@"
+CLT_FILENAME="Command_Line_Tools_${MACOS_VERSION}.pkg"
 FUSION_INVENTORY_AGENT_PKG="@@FUSION_INVENTORY_AGENT_PKG@@"
 FUSION_INVENTORY_AGENT_ARCHIVE="@@FUSION_INVENTORY_AGENT_ARCHIVE@@"
 VNC_SERVER_FILENAME="@@VNC_SERVER_FILENAME@@"
@@ -39,21 +40,20 @@ echo "1. INSTALLING COMMAND LINE TOOLS"
 echo "################################"
 echo
 
-touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
-case ${MACOS_VERSION} in
-	"10.13*" )
-    softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.0"
-		;;
-  "10.12*" )
-    softwareupdate -i "Command Line Tools (macOS Sierra version 10.12) for Xcode-9.0"
-    ;;
-  "10.11*" )
-    softwareupdate -i "Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2"
-    ;;
-  "10.10*" )
-    softwareupdate -i "Command Line Tools (macOS Yosemite version 10.10) for Xcode-7.2"
-    ;;
-esac
+if which cc; then
+  # Install Command Line Tools only if cc is not found
+  curl -O ${BASE_URL}/mac/downloads/${CLT_FILENAME}
+  if [[ -f ${CLT_FILENAME} ]];then
+    installer -store -pkg "${CLT_FILENAME}" -target /
+  else
+    echo "ERROR: downloaded package ${CLT_FILENAME} not found"
+    exit 1
+  fi
+  if [ -e ${CLT_FILENAME} ];then
+    rm -rf ${CLT_FILENAME}
+  fi
+fi
+
 
 # Homebrew
 su - $USER -c '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null'
